list: $/danielbecerra/urtseguimiento/models/listachequeoitems/columns.yaml
modelClass: DanielBecerra\UrtSeguimiento\Models\ListaChequeoItems
title: ListaChequeoItems
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'danielbecerra/urtseguimiento/listachequeoitems/update/:id'
