title: Visitas
modelClass: DanielBecerra\UrtSeguimiento\Models\Visitas
list: $/danielbecerra/urtseguimiento/models/visitas/columns.yaml
recordUrl: 'danielbecerra/urtseguimiento/visitas/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: $/danielbecerra/urtseguimiento/models/visitas/scopes.yaml