list: $/danielbecerra/ajustes/models/estados/columns.yaml
modelClass: DanielBecerra\Ajustes\Models\Estados
title: Estados
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'danielbecerra/ajustes/estados/update/:id'
