list: $/danielbecerra/ajustes/models/departamentos/columns.yaml
modelClass: DanielBecerra\Ajustes\Models\Departamentos
title: Departamentos
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'danielbecerra/ajustes/departamentos/update/:id'
